---
title: "PS270 Final Project"
author: "Evelyn Berg"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to presidential approval ratings, particularly how they change or do not change after major scandals. Though it also may be interesting to research how these ratings are affected by changes in the economy like oil prices, unemployment, and inflation. Another factor could be related to foreign conflicts. On a different note, I am additionally interested in researching teacher salaries in areas of varying wealth and resources.


## Milestone 2

```{r}
library(haven)
data <- read_dta("Data.dta")
head(data)
```

My research question is how does  electoral integrity after national-level elections vary across the world? In this project, I will look at values representing electoral integrity for a number of different countries. I hypothesize that electoral integrity will tend to be higher in countries in the more developed global north than the global south. Moreover, I expect that it will be higher in the most democratic countries in the data set. I expect these findings because stability is very conducive to government legitimacy. My data is taken from 170 countries across 643 elections. My explanatory variables of interest are the different countries studied in the data. My outcome variable of interest is electoral integrity. This is measured through an index of 64 indicators that make up 11 categories. In my data, an observed pattern of higher scores in more developed countries would support my hypothesis. On the other hand, higher scores in less developed countries would disprove my hypothesis. 

